services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    EzSystems\BehatBundle\API\ContentData\FieldTypeData\FieldTypeDataProviderInterface:
      tags: ['ezsystems.behat.fieldtype_data_provider']

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\RandomDataGenerator:
    arguments:
      - '@ezpublish.api.service.search'

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\ObjectRelationDataProvider:
    arguments:
      - '@ezpublish.api.service.search'
      - '@ezpublish.api.service.content'

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\ObjectRelationListDataProvider:
    arguments:
      - '@ezpublish.api.service.search'
      - '@ezpublish.api.service.content'

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\AuthorDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\BinaryFileDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\BooleanDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\CountryDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\DateDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\DateTimeDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\EmailDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\FloatDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\ISBNDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\ImageDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\IntegerDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\MapDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\MediaDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\PasswordProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\RichTextDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\StringDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\TextLineDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\TimeDataProvider: ~

  EzSystems\BehatBundle\API\ContentData\FieldTypeData\URLDataProvider: ~
