services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\BehatBundle\Subscriber\CreateContentDraft: ~

    EzSystems\BehatBundle\Subscriber\PublishDraft: ~

    EzSystems\BehatBundle\Subscriber\EditContent: ~
