services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ibexa\Bundle\Behat\Subscriber\EndScenarioSubscriber:
      tags:
        - { name: event_dispatcher.subscriber }
