services:

    ezbehatbundle.core.behat.context_argument_resolver:
        class: EzSystems\Behat\Core\Behat\AnnotationArgumentResolver
        tags:
            -  { name: context.argument_resolver, priority: 100 }