ez_platform_behat_repository_unauthorized_exception:
    path: '/platform-behat/exceptions/repository-unauthorized'
    defaults:
        _controller: 'ezbehatbundle.controller.exception:throwRepositoryUnauthorizedAction'
