 # File meant for services using services available in Ibexa DXP (Experience or higher)

imports:
     - { resource: services/stages.yaml }

services:
     _defaults:
         autowire: true
         autoconfigure: true
         public: false

     EzSystems\BehatBundle\Command\CreateExampleDataCommand: ~

     EzSystems\BehatBundle\Command\CreateExampleDataManagerCommand:
       arguments:
         - '%kernel.environment%'
         - '%kernel.project_dir%'
