name: Browser tests

on:
    push:
        branches:
            - master
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    admin-ui:
        name: "Admin UI tests"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^4.0.x-dev'
            test-suite:  '--profile=browser --suite=admin-ui-full'
            test-setup-phase-1: '--profile=regression --suite=setup-oss --mode=standard'
            ci-scripts-branch: adapt-to-new-symfony-recipes
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    examples:
        name: "BehatBundle examples"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'oss'
            project-version: '^4.0.x-dev'
            test-suite:  '--mode=standard --profile=service --suite=examples'
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
