services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Behat\API\Context\ContentContext:
        public: true
        arguments:
            $contentFacade: '@Ibexa\Behat\API\Facade\ContentFacade'
            $argumentParser: '@Ibexa\Behat\Core\Behat\ArgumentParser'

    Ibexa\Behat\API\Context\TrashContext:
        public: true
        arguments:
            $trashFacade: '@Ibexa\Behat\API\Facade\TrashFacade'
            $argumentParser: '@Ibexa\Behat\Core\Behat\ArgumentParser'

    Ibexa\Behat\API\Context\ContentTypeContext:
        public: true
        arguments:
            $contentTypeFacade: '@Ibexa\Behat\API\Facade\ContentTypeFacade'

    Ibexa\Behat\API\Context\LanguageContext:
        public: true
        arguments:
            $languageFacade: '@Ibexa\Behat\API\Facade\LanguageFacade'

    Ibexa\Behat\API\Context\ObjectStateContext:
        public: true
        arguments:
            $objectStateService: '@ibexa.api.service.object_state'

    Ibexa\Behat\API\Context\RoleContext:
        public: true
        arguments:
            $roleFacade: '@Ibexa\Behat\API\Facade\RoleFacade'
            $argumentParser: '@Ibexa\Behat\Core\Behat\ArgumentParser'

    Ibexa\Behat\API\Context\TestContext:
        public: true
        arguments:
            $userService: '@ibexa.api.service.user'
            $permissionResolver: '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Behat\API\Context\UserContext:
        public: true
        arguments:
            $userFacade: '@Ibexa\Behat\API\Facade\UserFacade'
            $argumentParser: '@Ibexa\Behat\Core\Behat\ArgumentParser'

    Ibexa\Behat\Core\Context\ConfigurationContext:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'

    Ibexa\Behat\Core\Context\FileContext:
        public: true
        arguments:
            $projectDirectory: '%kernel.project_dir%'

    Ibexa\Behat\Browser\Context\AuthenticationContext: ~

    Ibexa\Behat\Browser\Context\DebuggingContext:
        public: true
        arguments:
            $logger: '@logger'
            $logDir: '%kernel.logs_dir%'

    Ibexa\Behat\Core\Context\TimeContext: ~

    Ibexa\Behat\Browser\Context\ContentPreviewContext: ~

    Ibexa\Behat\Browser\Context\BrowserContext: ~
