services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Behat\Browser\Element\Factory\ElementFactory: ~

    Ibexa\Behat\Browser\Element\Factory\ElementFactoryInterface: '@Ibexa\Behat\Browser\Element\Factory\ElementFactory'

    Ibexa\Behat\Browser\Element\Factory\Debug\Interactive\ElementFactory:
        autowire: false
        decorates: Ibexa\Behat\Browser\Element\Factory\ElementFactory
        arguments: 
          - '@.inner'
