services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\Behat\Test\Factory\ElementFactory: ~

    EzSystems\Behat\Test\Factory\PageObjectFactory: ~

    EzSystems\Behat\Test\Factory\ElementFactoryInterface: '@EzSystems\Behat\Test\Factory\ElementFactory'

    EzSystems\Behat\Test\Factory\PageObjectFactoryInterface: '@EzSystems\Behat\Test\Factory\PageObjectFactory'

    EzSystems\Behat\Test\Session:
        lazy: true
        decorates: Behat\Mink\Session
        arguments: ['@EzSystems\Behat\Test\Session.inner']
